cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.cart_detail, name='cart_detail'),
	url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
	url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

ecommerce/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^career/', include('career.urls', namespace='career')),
    url(r'^contact/', include('contact.urls', namespace='contact')),
    url(r'^about/', include('static_pages.urls', namespace='static_pages')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^', include('product.urls', namespace='product')),
]
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^create/$', views.order_create, name='order_create'),
]

orders/models.py
from django.db import models
from product.models import Product
from profiles.models import UserProfile
from django_countries.fields import CountryField

class Order(models.Model):
	#I am making the user field as Null-True to allow Anynomous users to purchase
	user = models.ForeignKey(UserProfile, related_name='items', null=True)
	first_name = models.CharField(max_length=50)
	last_name = models.CharField(max_length=50)
	email = models.EmailField()
	phone = models.CharField(max_length=100 )
	address = models.CharField(max_length=250)
	country = CountryField(blank_label='(select country)',blank=True)
	city = models.CharField(max_length=100)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)    
	paid = models.BooleanField(default=False)

	class Meta:
		ordering = ('-created',)

	def __str__(self):
		return 'Order {}'.format(self.id)

	def get_total_cost(self):
		return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
	order = models.ForeignKey(Order, related_name='items')
	product = models.ForeignKey(Product, related_name='order_items')
	price = models.DecimalField(max_digits=10, decimal_places=2)
	quantity = models.PositiveIntegerField(default=1)

	def __str__(self):
		return '{}'.format(self.id)

	def get_cost(self):
		return self.price * self.quantity

orders/forms.py
from django import forms
from .models import Order

class OrderCreateForm(forms.ModelForm):
	class Meta:
		model = Order
		fields = ['first_name', 'last_name', 'email', 'phone','address', 
                  'country', 'city']

orders/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart
from django.contrib.auth.decorators import login_required



@login_required
def order_create(request):
	cart = Cart(request)
	if request.method == 'POST':
		form = OrderCreateForm(request.POST)
		if form.is_valid():
			'''
			It is advisable to handle empty cart with orders that is 0 cost
			'''
			order = form.save(commit=False)
			order.user = request.user
			order = form.save()
			for item in cart:
				OrderItem.objects.create(order=order, product=item['product'], price=item['price'], quantity=item['quantity'])  
			# clear the cart
			cart.clear()
			return render(request, 'orders/order_detail.html', {'order': order})
	else:
		form = OrderCreateForm()
	return render(request, 'orders/order_detail.html', {'cart': cart, 'form': form})

orders/templates/orders/order_detail.html
{% extends "base.html" %}

{% load i18n %}

{% load static %}
{% block title %}
  Order Details
{% endblock %}

{% block content %}


  <!-- Bread Crumb STRAT -->
  <div class="container">
    <div class="bread-crumb mtb-30 center-xs">
      <div class="page-title">Order</div>
      <div class="bread-crumb-inner right-side float-none-xs">
        <ul>
          <li><a href="index.html">Home</a><i class="fa fa-angle-right"></i></li>
          <li><a href="cart.html">Order</a><i class="fa fa-angle-right"></i></li>
          <li><span>Order Details</span></li>
        </ul>
      </div>
    </div>
  </div>
  <!-- Bread Crumb END -->
  
  <!-- CONTAIN START -->
  <section class="checkout-section pb-95">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">


          <div class="checkout-step mb-40">
            <ul>
              <li> 
                <a href="#">
                  <div class="step">
                    <div class="line"></div>
                    <div class="circle">1</div>
                  </div>
                  <span>Shopping Cart</span>
                </a>
              </li>
              <li class="active"> 
                <a href="#">
                  <div class="step">
                    <div class="line"></div>
                    <div class="circle">2</div>
                  </div>
                  <span>Order Overview</span>
                </a>
              </li>
              <li>
                <a href="#">
                  <div class="step">
                    <div class="line"></div>
                    <div class="circle">3</div>
                  </div>
                  <span>Payment</span>
                </a>
              </li>
              <li>
                <a href="#">
                  <div class="step">
                    <div class="line"></div>
                    <div class="circle">4</div>
                  </div>
                  <span>Order Complete</span>
                </a>
              </li>
            </ul>
            <hr>
          </div>



          <div class="checkout-content" >

            <div class="row">
              <div class="col-xs-12">
                <div class="heading-part align-center">
                    <h2 class="heading">Please fill up your Order details</h2>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-xs-12">
                <div class="heading-part align-center">
                    {{form.non_field_errors}}
                </div>
              </div>
            </div>



            <div class="row">


              <div class="col-sm-6 mb-sm-30">
                <form action="." method="post" class="main-form full">
                  {% csrf_token %}
                  <div class="">
                    <div class="row">

                      <div class="col-xs-12 mb-20">
                        <div class="heading-part">
                          <h3 class="sub-heading">Shipping Address</h3>
                        </div>
                        <hr>
                      </div>

                      <div class="col-sm-6">
                        <div class="input-box {% if form.first_name.errors %} has-error {% endif %}">
                          <input  maxlength="150" 
                            name="first_name"  
                                id="id_first_name" 
                                type="text" 
                                 value="{{user.first_name}}"  
                                placeholder="First Name*" 
                                class="form-control "
                                />
                          <span class='error'>{{  form.first_name.errors }}</span>
                        </div>
                      </div>

                      <div class="col-sm-6">
                        <div class="input-box {% if form.last_name.errors %} has-error {% endif %}">
                          <input  maxlength="150" 
                            name="last_name"  
                                id="id_first_name" 
                                type="text" 
                                 value="{{user.last_name}}"  
                                placeholder="Last Name*" 
                                class="form-control "
                                />
                          <span>{{  form.last_name.errors }}</span>
                        </div>
                      </div>

                      <div class="col-sm-6">
                        <div class="input-box {% if form.email.errors %} has-error{% endif %}">
                              <input  id="id_email" 
                                  maxlength="50" 
                                  name="email" 
                                  type="email" 
                                  value="{{user.email}}" 
                                  placeholder="Email Address*" 
                                  class="form-control"
                                  />
                              <span>{{  form.email.errors }}</span>
                        </div>
                      </div>

                      <div class="col-sm-6">
                          <div class="input-box {% if form.phone.errors %} has-error{% endif %}">
                          <input  id="id_phone" 
                              maxlength="16" 
                              name="phone" 
                              placeholder="Phone Number" 
                              type="text" 
                              {% if user.phone %} value="{{user.phone}}" {% endif %}
                              class="form-control"
                              />
                          <span>Tel. Format: +XXX YYY YYY</span>
                          <span>{{  form.phone.errors }}</span>
                          </div>
                      </div>

                      <div class="col-sm-6">
                        <div class="input-box {% if form.country.errors %} has-error {% endif %}">
                          <select   id="id_country" name="country" class="form-control">
                              <option 
                                selected="selected"  
                                value="{% if user.nationality != '' %}{{user.nationality}}{% endif %}"
                                >
                                {% if user.nationality != '' %} {{user.nationality}}  {% else %}  Select Shipping Country {% endif %} 
                                </option>
                                {% for value, text in form.country.field.choices %}
                                    <option value="{{ value }}"{% if user.nationality == value %} selected{% endif %}>{{ text }}</option>
                                {% endfor %}
                          </select>
                          <span> Please select Shipping Country</span>
                          <span>{{  form.nationality.errors }}</span>
                        </div>
                      </div>

                      <div class="col-sm-6">
                        <div class="input-box {% if form.city.errors %} has-error {% endif %}">
                          <input  maxlength="150" 
                            name="city"  
                                id="id_city" 
                                type="text" 
                                placeholder="Shipping City Name" 
                                class="form-control "
                                 
                                />
                          <span>{{  form.city.errors }}</span>
                        </div>
                      </div>

                      <div class="col-sm-12">
                        <div class="input-box {% if form.address.errors %} has-error {% endif %}">
                          <input  maxlength="150" 
                            name="address"  
                                id="id_address" 
                                type="text"  
                                placeholder="Shipping Address" 
                                class="form-control "
                                />
                          <span>Please provide the number and street.</span>
                          <span>{{  form.address.errors }}</span>
                        </div>
                      </div>

                      <div class="col-sm-12">
                        <button type="submit" value="Submit" class="btn-black right-side"  name="submit">Next</button>
                      </div>

                    </div>
                  </div>
                </form>
              </div>





              <div class="col-sm-6 mb-sm-30">
                <div class="cart-item-table commun-table mb-30">
                  <div class="table-responsive">
                    <table class="table">
                      <thead>
                        <tr>
                          <th>Product</th>
                          <th>Product Detail</th>
                          <th>Sub Total</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for item in cart %}
                          {% with product=item.product %}
                          <tr>
                            <td>
                              <a href="product-page.html">
                                <div class="product-image"><a href="{{ product.get_absolute_url }}"><img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}"> </a></div>
                              </a>
                            </td>
                            <td>
                              <div class="product-title">
                                <a href="{{ product.get_absolute_url }}"> {{ product.name }}</a>
                                <div class="product-info-stock-sku m-0">
                                  <div>
                                    <label>Price: </label>
                                    <div class="price-box">
                                      <span class="info-deta price">${{ item.price }}</span>
                                    </div>
                                  </div>
                                </div>
                                <div class="product-info-stock-sku m-0">
                                  <div>
                                    <label>Quantity: </label>
                                    <span class="info-deta">${{ item.quantity }}</span>
                                  </div>
                                </div>
                              </div>
                            </td>
                            <td>
                              <div data-id="100" class="total-price price-box">
                                  <span class="price">${{ item.total_price }}</span>
                              </div>
                            </td>
                          </tr>
                          {% endwith %}
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>



                <div class="cart-total-table commun-table mb-30">
                  <div class="table-responsive">
                    <table class="table">
                      <thead>
                        <tr>
                          <th colspan="2">Cart Total</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td>Item(s) Subtotal</td>
                          <td>
                            <div class="price-box">
                              <span class="price">${{ cart.get_total_price }}</span>
                            </div>
                          </td>
                        </tr>
                        <tr>
                          <td>Shipping</td>
                          <td>
                            <div class="price-box">
                              <span class="price">$0</span>
                            </div>
                          </td>
                        </tr>
                        <tr>
                          <td><b>Total Amount Payable</b></td>
                          <td>
                            <div class="price-box">
                              <span class="price"><b>${{ cart.get_total_price }}</b></span>
                            </div>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>



            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- CONTAINER END --> 


{% endblock %}