career/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [ 
		url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/new_resume/$',views.new_resume,name='new_resume'),   
		url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',views.vacancy_detail,name='vacancy_detail'),
		url(r'^$', views.vacancy_list,name='vacancy_list'),
	]

cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.cart_detail, name='cart_detail'),
	url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
	url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

ecommerce/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^career/', include('career.urls', namespace='career')),
    url(r'^contact/', include('contact.urls', namespace='contact')),
    url(r'^about/', include('static_pages.urls', namespace='static_pages')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^', include('product.urls', namespace='product')),
]
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

career/models.py
from django.db import models
from django.utils.timezone import now
from django.utils import timezone
# For the Slug Field
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify
# For the country Field
from django_countries.fields import CountryField
#Used for the Telephone Field validation
from django.core.validators import RegexValidator



class Vacancy(models.Model):

	title = models.CharField(max_length=150, unique=True,db_index=True)
	slug = models.CharField(max_length=150, unique=True)
	job_summary = models.TextField(blank=True, null=True)
	location = CountryField(blank_label='(select country)')
	responsibilities = models.TextField(blank=True, null=True)
	requirements = models.TextField(blank=True, null=True)
	is_published = models.BooleanField(default=True, verbose_name="Publish?") 
	created_timestamp = models.DateField( auto_now_add=True)


	def get_absolute_url(self):
		return reverse('career:vacancy_detail', args=[self.id, self.slug])
		#return "/vacancy/%s/" % self.slug

	class Meta:
		ordering = ("is_published","title",)
		index_together = (('id', 'slug'),)
		verbose_name = 'Vacancy'
		verbose_name_plural = 'Vacancies'

	def save(self, *args, **kwargs):
		#if (self.date_added is None):
		#	self.date_added = now()
		# for replacing all spaces inside the titile and copy the result to the Slug before saving
		self.slug = slugify(self.title)
		# for preserving line breaks inside
		#self.responsibilities = self.responsibilities.replace("\n", "<br/>")
	
		super(Vacancy, self).save(*args, **kwargs)

	def __str__(self):
		return self.title



class Resume(models.Model):

	phone_regex = RegexValidator(regex=r'^\+?1?\d{8,15}$', 
		message="Phone number must be entered in the format: '+999999'. Min of 5 digits and max Up to 15 digits allowed.")

	vacancy = models.ForeignKey(Vacancy)
	first_name = models.CharField(max_length=150)
	middle_name = models.CharField(max_length=150, blank=True, null=True)
	last_name = models.CharField(max_length=150)
	nationality = models.CharField(max_length=150,)
	birth_date = models.DateField()
	phone = models.CharField(validators=[phone_regex], max_length=16) 
	email = models.EmailField(max_length=50)
	comment = models.CharField(max_length=500, help_text="Please Enter any comments", blank=True, null=True)
	resume_file = models.FileField(upload_to='career/%Y/%m/%d/')
	applied_timestamp = models.DateField(auto_now_add=True);

	class Meta:
		ordering = ("applied_timestamp",)
#	def save(self, *args, **kwargs):
#		if (self.date_added is None):
#			self.date_added = now()
#		super(career, self).save(*args, **kwargs)

career/forms.py
from django import forms

# Required for the Career Forms
from django.forms import ModelForm, Textarea,TextInput
from .models import Resume
from django.utils.translation import ugettext_lazy as _
from django.forms.extras import SelectDateWidget
import datetime
import os
from django.core.exceptions import ValidationError
'''
Form for Subitting a Job
'''
class ResumeForm(ModelForm): 
	
	class Meta:
		model = Resume
		fields = ['first_name', 'middle_name' ,'last_name' ,'nationality' ,'birth_date' ,'phone' ,'email' ,'comment' ,'resume_file']   # Or a list of the fields that you want to include in your form without it will get Error  "Creating a ModelForm without either the 'fields'"
		#years_to_display = range(datetime.datetime.now().year - 100, datetime.datetime.now().year)

		#widgets = {
          #  'comment': Textarea(attrs={'cols': 60, 'rows': 6}),
          #  'birth_date': SelectDateWidget(years=years_to_display),
         #   'phone': TextInput(attrs={'placeholder': '+XXX YYY YYY'}),
        #}

		#labels = {
		#	'resume_file': _('Upload Resume'),
		#}

	def clean_resume_file(self):
		"""
			Validate the submitted file to use an acceptable extension + an acceptable size
		"""
		file = self.cleaned_data.get("resume_file", False)
		# check file extension 
		ext = os.path.splitext(file.name)[1]  # [0] returns extension only
		valid_extensions = ['.pdf', '.doc', '.docx']
		if not ext.lower() in valid_extensions:
			raise ValidationError(u'Unsupported file extension.')
		# check file size
		if file._size > 4*1024*1024:
			raise ValidationError("file size is too large ( > 4mb )")

		return file

career/views.py
from django.shortcuts import render, get_object_or_404
# used for pagnation
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
#used for my customized created models
from .models import Vacancy, Resume

from .forms import ResumeForm
from django.http import HttpResponse

def vacancy_list(request):
		"""
			For displying All vacancies
		"""
		#for listing Categories on the lift side of the page
		vacancies = Vacancy.objects.filter(is_published=True)

		# Pagination
		paginator = Paginator(vacancies, 5) # Show 25 contacts per page
		page = request.GET.get('page')
		try:
			page_list = paginator.page(page)
		except PageNotAnInteger:
			# If page is not an integer, deliver first page.
			page_list = paginator.page(1)
		except EmptyPage:
			# If page is out of range (e.g. 9999), deliver last page of results.
			page_list = paginator.page(paginator.num_pages)

		# Fixing the proplem f the reptitave Page attribute in URL
		url_without_page = request.GET.copy()
		if 'page' in url_without_page:
			del url_without_page['page']

		# FInal Context Variables to Send
		context = {
			'page_list': page_list,
			'url_without_page':url_without_page,
		}
		return render(request,'career/vacancy_list.html', context)



def vacancy_detail(request, id, slug):
		"""
			For displying All information related to ONE vacancy
		"""
		vacancy = get_object_or_404(Vacancy,id=id,slug=slug,is_published=True)

		# Final Context Variables to Send back
		context = {
			'vacancy': vacancy,
		}
		return render(request,'career/vacancy_detail.html', context)



def new_resume(request, id, slug):
		"""
			Submit a new resume to an exiting Vacancy
		"""
		vacancy =  get_object_or_404(Vacancy,id=id,is_published=True)
		# Get the context from the request
		resume = None
		if request.method == 'POST':
			# Create a form instance and populate it with data from the request (binding):
			form=ResumeForm(request.POST, request.FILES)
			if form.is_valid():
				#check if the same email used for the same vacancy before
				resume = Resume.objects.filter(email=form.cleaned_data['email']).filter(vacancy= vacancy)
				if not resume:
					resume = form.save(commit=False)
					resume.vacancy = vacancy
					resume.first_name = form.cleaned_data['first_name']
					resume.middle_name = form.cleaned_data['middle_name']
					resume.last_name = form.cleaned_data['last_name']
					resume.nationality = form.cleaned_data['nationality']
					resume.birth_date = form.cleaned_data['birth_date']
					resume.phone = form.cleaned_data['phone']
					resume.email = form.cleaned_data['email']
					resume.comment = form.cleaned_data['comment']
					resume.resume_file = form.cleaned_data['resume_file']
					resume.save()
					context = {
						'message':"You Resume has Been submitted", 
					}
					return render(request, "career/resume_status.html", context)
				else:
					context = {
						'message':"A resume from this email is already submitted to this Vacancy", 
					}
					return render(request, "career/resume_status.html", context)
		else:
			# Not a POST so Generate New Empty Form from Resume Class
			form = ResumeForm()

		context = {
			'form': form,
			'vacancy':vacancy,
		}
		return render(request, "career/new_resume.html", context)

career/templates/career/new_resume.html
{% extends "base.html" %}
{% load static %}

{% block title %}
	New Resume
{% endblock %}

{% block content %}  

  <!-- Bread Crumb STRAT -->
  <div class="container">
    <div class="bread-crumb mtb-30 center-xs">
      <div class="page-title">Career</div>
      <div class="bread-crumb-inner right-side float-none-xs">
        <ul>
          <li><a href="/">Home</a><i class="fa fa-angle-right"></i></li>
          <li><a href="/career/">Career</a><i class="fa fa-angle-right"></i></li>
          <li>Apply to Jop</li>
        </ul>
      </div>
    </div>
  </div>
  <!-- Bread Crumb END --> 

<form action="" class="main-form full" enctype="multipart/form-data" method="POST" >
{% csrf_token %}
  <section class="checkout-section pb-95">
    <div class="container">
      <div class="row">
		    <div class="col-xs-12">
         <div class="checkout-content" >


            <div class="row">
              <div class="col-xs-12">
                <div class="heading-part align-center">
                    <h2 class="heading">Please fill up your details</h2>
                </div>
              </div>
            </div>
 


            <div class="row">
              <div class="col-lg-6 col-md-8 col-sm-8 col-lg-offset-3 col-sm-offset-2">


                  <div class="mb-20">
                    <div class="row ">
                    	<div class="col-sm-12">
                        	<div class="input-box">
                    			{{form.non_field_errors}}{{form.resume_file.errors }} 
                    		</div>
                 		 </div>
                    </div>
                  </div>

                  <div class="mb-20">
                    <div class="row">



                      <div class="col-sm-6">
                        <div class="input-box {% if form.first_name.errors %} has-error {% endif %}">
                        	<input  maxlength="150" 
                        	name="first_name"  
                        			id="id_first_name" 
                        			type="text" 
                        			{% if form.first_name.value %} value="{{form.first_name.value}}" {% endif %} 
                        			placeholder="First Name*" 
                        			class="form-control "
                        			/>
                        </div>
                      </div>
                      <div class="col-sm-6">
                        <div class="input-box {% if form.middle_name.errors %} has-error {% endif %}" >
                          	<input 	id="id_middle_name" 
                          			maxlength="150" 
                          			name="middle_name" 
                          			type="text" 
                          			{% if form.middle_name.value %} value="{{form.middle_name.value}}" {% endif %} 
                          			placeholder="Middle Name" 
                          			class="form-control" 
                          			/>
                        </div>
                      </div>
                      <div class="col-sm-6">
                        <div class="input-box {% if form.last_name.errors %} has-error{% endif %}">
                          	<input id="id_last_name" 
                          			maxlength="150" 
                          			name="last_name" 
                          			type="text" 
                          			{% if form.last_name.value %} value="{{form.last_name.value}}" {% endif %} 
                          			placeholder="Last Name*" 
                          			class="form-control"
                          			/>
                        </div>
                      </div>


                      <div class="col-sm-6">
                        <div class="input-box {% if form.email.errors %} has-error{% endif %}">
                          	<input 	id="id_email" 
                          			maxlength="50" 
                          			name="email" 
                          			type="email" 
                          			{% if form.email.value %} value="{{form.email.value}}" {% endif %}
                          			placeholder="Email Address*" 
                          			class="form-control"
                          			/>
                        </div>
                      </div>


                      <div class="col-sm-6">
                        <div class="input-box {% if form.phone.errors %} has-error{% endif %}">
                        <input 	id="id_phone" 
                        		maxlength="16" 
                        		name="phone" 
                        		placeholder="Phone*" 
                        		type="text" 
                        		{% if form.phone.value %} value="{{form.phone.value}}" {% endif %}
                        		class="form-control"
                        		/>
                        <span>Tel. Format: +XXX YYY YYY</span>
                        </div>
                      </div>

                      <div class="col-sm-6">
                        <div class="input-box {% if form.birth_date.errors %} has-error{% endif %}">
                          	 <input id="id_birth_date" 
                          	 		maxlength="50" 
                          	 		name="birth_date" 
                          	 		type="text" 
                          	 		{% if form.birth_date.value %} value="{{form.birth_date.value}}" {% endif %}
                          	 		placeholder="Birth Date*" 
                          	 		class="form-control" 
                          	 		/>
                          	 <span> YYYY-MM-DD</span>
                        </div>
                      </div>

                      <div class="col-sm-6">
                        <div class="input-box {% if form.nationality.errors %} has-error {% endif %}">
                          <select 	id="id_nationality" name="nationality" class="form-control">
                          		<option 
                          			selected="selected"  
                          			value="{% if form.nationality.value %} {{form.nationality.value}}  {% endif %}"
                          			>
                          			{% if form.nationality.value %} {{form.nationality.value}} {% else %} Select Nationality* {% endif %} 
                          			</option>
									            {% include '_countries_list.html' %}
						              </select>
						              <span> Please select Your Nationality</span>
                        </div>
                       </div>
                    
                      <div class="col-sm-6">
                        <div class="input-box {% if form.resume_file.errors %} has-error {% endif %} ">
                          	<input 	id="id_resume_file" 
                          			name="resume_file" 
                          			type="file" 
                          			class="form-control"
                          			/>
                          <span>Please upload resume* (max 4mb using (pdf, doc, docx)</span>
                        </div>
                      </div>

                      <div class="col-sm-12">
                        <div class="input-box {% if form.comment.errors %} has-error {% endif %}">
                          	<textarea cols="60" id="id_comment" 
                          			maxlength="500" 
                          			name="comment" rows="6" 
                          			placeholder="Please Enter any comments" 
                          			class="form-control"
                          			>{% if form.comment.value %} {{form.comment.value}} {% endif %}</textarea>
                        </div>
                      </div>

                    </div>
                  </div>

                  <button type="submit" value="Submit" class="btn-black"  name="submit">Apply</button>
              </div>
            </div>


         </div>
        </div>
      </div>
    </div>
  </section>
</form>

{% endblock %}

career/templates/career/resume_status.html
{% extends "base.html" %}
{% load static %}

{% block title %}
	Career
{% endblock %}

{% block content %}  


  <!-- Bread Crumb STRAT -->
  <div class="container">
    <div class="bread-crumb mtb-30 center-xs">
      <div class="page-title">Career</div>
      <div class="bread-crumb-inner right-side float-none-xs">
        <ul>
          <li><a href="/">Home</a><i class="fa fa-angle-right"></i></li>
          <li><a href="/career/">Career</a><i class="fa fa-angle-right"></i></li>
          <li>Submition Status</li>
        </ul>
      </div>
    </div>
  </div>
  <!-- Bread Crumb END --> 


 <section class="pb-95">
    <div class="container">

              <div class="col-xs-12">
                <div class="heading-part align-center">
                    <h2 class="heading">{{ vacancy.title }}</h2>
                </div>
              </div>

            <div class="row">
              <div class="col-lg-10 col-md-8 col-sm-8 col-lg-offset-1 col-sm-offset-1">
                <div class="payment-option-box mb-30">
                  <div class="payment-option-box-inner ">
                    <div class="payment-top-box">
                      <div class="radio-box left-side">
                        <label for="paypal">{{ message }}</label>
                      </div>
                    </div>
                    <p>Please feel free to check other vacancies which may suite your experience. <span> <a href="/career/">Click Here</a> </span> </p>
                  </div>
                </div>
               </div>
            </div>
    </div>
</section>
<!-- CONTENTS ENDS -->

{% endblock %}

career/templates/career/vacancy_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
	Career
{% endblock %}

{% block content %}  


  <!-- BANNER STRAT -->
  <div class="banner career-banner"></div>
  <!-- BANNER END --> 


  <!-- Bread Crumb STRAT -->
  <div class="container">
    <div class="bread-crumb mtb-30 center-xs">
      <div class="page-title">Career</div>
      <div class="bread-crumb-inner right-side float-none-xs">
        <ul>
          <li><a href="/">Home</a><i class="fa fa-angle-right"></i></li>
          <li><a href="/career/">Career</a><i class="fa fa-angle-right"></i></li>
          <li>Jop Details</li>
        </ul>
      </div>
    </div>
  </div>
  <!-- Bread Crumb END --> 


 <section class="pb-95">
    <div class="container">

              <div class="col-xs-12">
                <div class="heading-part align-center">
                    <h2 class="heading">{{ vacancy.title }}</h2>
                </div>
              </div>



            <div class="row">
              <div class="col-lg-10 col-md-8 col-sm-8 col-lg-offset-1 col-sm-offset-1">

                <div class="payment-option-box mb-30">
                  <div class="payment-option-box-inner ">
                    <div class="payment-top-box">
                      <div class="radio-box left-side">
                        <label for="paypal">Job Summary ( Location: {{ vacancy.location.name }})</label>
                      </div>
                    </div>
                    <p>{{ vacancy.job_summary|linebreaks }}</p>
                  </div>
                </div>

                <div class="payment-option-box mb-30">
                  <div class="payment-option-box-inner ">
                    <div class="payment-top-box">
                      <div class="radio-box left-side">
                        <label for="paypal">Responsibilities </label>
                      </div>
                    </div>
                    {{ vacancy.responsibilities|linebreaks}}
                  </div>
                </div>



                <div class="payment-option-box mb-30">
                  <div class="payment-option-box-inner ">
                    <div class="payment-top-box">
                      <div class="radio-box left-side">
                        <label for="paypal">Requirements </label>
                      </div>
                    </div>
                    <p>{{ vacancy.requirements|linebreaks}}</p>
                  </div>
                </div>


                <div class="right-side float-none-xs">
                  <a class="btn btn-black" href="new_resume/">Apply Now<span><i class="fa fa-angle-right"></i></span></a>
                </div>
              </div>
            </div>





    </div>
</section>
<!-- CONTENTS ENDS -->

{% endblock %}

career/templates/career/vacancy_list.html
{% extends "base.html" %}
{% load staticfiles %}


{% block title %}  
	Career
{% endblock %}


{% block content %}  
	  

  <!-- BANNER STRAT -->
  <div class="banner career-banner"></div>
  <!-- BANNER END --> 


  <!-- Bread Crumb STRAT -->
  <div class="container">
    <div class="bread-crumb mtb-30 center-xs">
      <div class="page-title">Career</div>
      <div class="bread-crumb-inner right-side float-none-xs">
        <ul>
          <li><a href="/">Home</a><i class="fa fa-angle-right"></i></li>
          <li><span>Career</span></li>
        </ul>
      </div>
    </div>
  </div>
  <!-- Bread Crumb END --> 




 <!-- COntents STRAT -->
 <section class="pb-95">
    <div class="container">
          <div class="row">
            {% if page_list|length > 0 %}
              <div class="col-xs-12 mb-xs-30">
                <div class="career-list-table commun-table">
                  <div class="table-responsive">
                    <table class="table">
                      <thead>
                        <tr>
	                       	<th>Vacancy</th> 
	                      	<th>Description</th>
	                      	<th></th>
	                        <th></th> 
                        </tr>
                      </thead>
                      <tbody>

	                      {% for vacancy in page_list %}
	                        <tr>
	                          <td >
	                            <a href="{{ vacancy.get_absolute_url }}" ><b>{{ vacancy.title }} </b></a>
	                          </td>
	                          <td>
	                            <div>
	                              <span class="info-deta">{{ vacancy.job_summary }}</span>
	                            </div>
	                          </td>
	                          <td>
	                  			<a href="{{ vacancy.get_absolute_url }}"  >Read More</a>
	                          </td>
	                          <td>
	                  			<a href="{{ vacancy.id }}/{{ vacancy.slug }}/new_resume/"><button class="btn-black"  name="submit">Apply</button></a>
	                          </td>
	                        </tr>
	                       {% endfor %}

                      </tbody>
                    </table>
                  </div>
                </div>
              </div>

            {%else%}
              <div class="col-xs-12">
                <div class="heading-part align-center">
                  </br>
                    <h3 class="heading">No Vacancies available for the time being.</h3>
                    <p>Please check again later.</p>
                    </br>
                </div>
              </div>
            {% endif %}

          </div>

      {% include '_paginator.html' %}

    </div>
</section>
<!-- CONTENTS ENDS -->
{% endblock %}