cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.cart_detail, name='cart_detail'),
	url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
	url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

ecommerce/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^career/', include('career.urls', namespace='career')),
    url(r'^contact/', include('contact.urls', namespace='contact')),
    url(r'^about/', include('static_pages.urls', namespace='static_pages')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^', include('product.urls', namespace='product')),
]
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

product/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [    
		url(r'^search', views.search_product,name='search'),
		url(r'^categories', views.category_list,name='categories'),
		url(r'^promotion', views.promotion_list,name='promotion_list'),
		url(r'^(?P<category_slug>[-\w]+)/$',views.product_list,name='product_list_by_category'),
		url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',views.product_detail,name='product_detail'),
		url(r'^$', views.product_list, name='product_list'),
	]

product/models.py
from django.db import models
from django.utils.timezone import now
from django.utils import timezone
# For the Slug Field
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

# Create your models here. 

class Product(models.Model):

	name = models.CharField(max_length=200, help_text="Please Enter a Generic Name")
	model = models.CharField(max_length=70, blank=True, null=True)
	slug = models.CharField(max_length=200, unique=True)
	description = models.TextField(blank=True, null=True)
	image = models.ImageField(upload_to='product/Media/%Y/%m/%d',blank=True)
	price = models.DecimalField(max_digits=10, decimal_places=2)
	stock = models.PositiveIntegerField(blank=True, null=True)
	show_stock = models.BooleanField(default=False, verbose_name="Show Stock Quantity?") 
	is_published = models.BooleanField(default=True, verbose_name="Publish?") 
	is_discounted = models.BooleanField(default=False, verbose_name="With Discount Offer?")
	discount_expire = models.DateTimeField(blank=True, null=True, verbose_name="Last Date for Discount")
	discounted_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True,null=True,verbose_name="After Discount Price")
	is_featured = models.BooleanField(default=False, verbose_name="Fetured Product?")
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	categories = models.ManyToManyField("Category",related_name="products")

	class Meta:
		ordering = ("name",)
		index_together = (('id', 'slug'),)

	def get_absolute_url(self):
		return reverse('product:product_detail',args=[self.id, self.slug])

	def clean(self):
		if self.is_discounted and (self.discounted_price is None or self.discounted_price > self.price):
			raise ValidationError(_('Discount Price is not set correctty although Discount option is checked'))

	def save(self, *args, **kwargs):
		# for replacing all spaces inside the titile and copy the result to the Slug before saving
		self.slug = slugify(self.name)
		super(Product, self).save(*args, **kwargs)

	def __str__(self):
		return self.name




class Category(models.Model):

	name = models.CharField(max_length=150, help_text="Please Enter A Name", unique=True)
	slug = models.CharField(max_length=150, unique=True)
	image = models.ImageField(upload_to='category/Media/%Y/%m/%d',blank=True,null=True)
	description = models.TextField(blank=True, null=True)

	def get_absolute_url(self):
		return reverse('product:product_list_by_category', args=[self.slug])

	class Meta:
		ordering = ('name',)
		index_together = (('id', 'slug'),)
		verbose_name = 'category'
		verbose_name_plural = 'categories'

	def save(self, *args, **kwargs):
		# for replacing all spaces inside the titile and copy the result to the Slug before saving
		self.slug = slugify(self.name)
		super(Category, self).save(*args, **kwargs)

	def __str__(self):
		return self.name

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 100)]

class CartAddProductForm(forms.Form):
	quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
	update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

product/forms.py
from django import forms

'''
From for searching a product
'''
class SearchForm(forms.Form):    
	search_query = forms.CharField(
			label='Search a Product',
			help_text='Type Product Name',
			required=False,
	)
	is_exact_match = forms.BooleanField(label='Exact Match',required=False)
	max_price = forms.DecimalField(max_digits=10, decimal_places=2 ,required=False)
	search_category = forms.CharField(required=False)
	show_count = forms.IntegerField(required=False)

product/views.py
from django.shortcuts import render, get_object_or_404
# used for pagnation
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
#used for my customized created models
from .models import Category, Product
from cart.forms import CartAddProductForm

from .forms import SearchForm
#used for normalizing my search text
import re




def product_list(request, category_slug=None):
		"""
			For displying All products and Categories
		"""
		#for listing Categories othat has at least one published product
		categories = Category.objects.filter(products__is_published=True).distinct()
		#List all products
		page_list = Product.objects.filter(is_published=True)
		show_count = None
		category = None
		

		# If this is a GET request then process the Form data
		if request.method == 'GET':
			# Create a form instance and populate it with data from the request (binding):
			form=SearchForm(request.GET)
			if form.is_valid():
				show_count = form.cleaned_data['show_count']
			

		# List Prodcuts based on Category
		if category_slug:
			category = get_object_or_404(Category, slug=category_slug)
			page_list = Product.objects.filter(categories__in=[category],is_published=True)
		
		# handeling Paganation & Items count per page
		if show_count:
			paginator = Paginator(page_list, show_count)
		else:
			 paginator = Paginator(page_list, 10)
			 show_count = 10
		page = request.GET.get('page')
		try:
			page_list = paginator.page(page)
		except PageNotAnInteger:
			# If page is not an integer, deliver first page.
			page_list = paginator.page(1)
		except EmptyPage:
			# If page is out of range (e.g. 9999), deliver last page of results.
			page_list = paginator.page(paginator.num_pages)
		
		# Fixing the proplem of the reptitave Page attribute in URL when using the paging links
		url_without_page = request.GET.copy()
		if 'page' in url_without_page:
			del url_without_page['page']

		# FInal Context Variables to Send
		context = {
			'category': category,
			'categories': categories,
			'page_list': page_list,
			'url_without_page':url_without_page,
			'show_count':show_count,
		}
		return render(request,'product/product_list.html', context)


def promotion_list(request, category_slug=None):
		"""
			For displying ONly Discounted and Featured products and Categories
		"""
		#for listing Categories on the lift side of the page
		categories = Category.objects.filter(products__is_discounted=True).distinct()
		products = Product.objects.filter(is_published=True).filter(is_discounted=True)
		
		# FInal Context Variables to Send
		context = {
			'categories': categories,
			'products': products,
		}
		return render(request,'product/promotion_list.html', context)




def category_list(request):
		"""
			For displying All Categories
		"""
		#for listing Categories othat has at least one published product
		page_list = Category.objects.filter(products__is_published=True).distinct()

		# Pagination
		paginator = Paginator(page_list, 9) # Show 25 contacts per page
		page = request.GET.get('page')
		try:
			page_list = paginator.page(page)
		except PageNotAnInteger:
			# If page is not an integer, deliver first page.
			page_list = paginator.page(1)
		except EmptyPage:
			# If page is out of range (e.g. 9999), deliver last page of results.
			page_list = paginator.page(paginator.num_pages)

		# Fixing the proplem f the reptitave Page attribute in URL
		url_without_page = request.GET.copy()
		if 'page' in url_without_page:
			del url_without_page['page']
		
		# FInal Context Variables to Send
		context = {
			'page_list': page_list,
			'url_without_page':url_without_page,

		}
		return render(request,'product/category_list.html', context)




def product_detail(request, id, slug):
		"""
			For displying All information related to ONE Products and listing all categories
		"""
		#for listing Categories othat has at least one published product
		categories = Category.objects.filter(products__is_published=True).distinct()
		product = get_object_or_404(Product,id=id,slug=slug,is_published=True)
		related_categories = product.categories.all()
		# Related products List has the same category as the current prodcut without repeatition. 
		related_products = Product.objects.filter(categories__in=list(related_categories)).exclude(id=product.id).distinct()
		#intializing the cart form
		cart_product_form = CartAddProductForm()
		# Final Context Variables to Send back
		context = {
			'categories': categories,
			'product': product,
			'related_products':related_products,
			'cart_product_form':cart_product_form
		}
		return render(request,'product/detail.html', context)



def search_product(request):
		"""
		This View will relay on the request context valriables anc check all posibilities/criterias and search the DB
		"""
		#for listing Categories othat has at least one published product
		categories = Category.objects.filter(products__is_published=True).distinct()

		# If this is a GET request then process the Form data
		if request.method == 'GET':
			# Create a form instance and populate it with data from the request (binding):
			form=SearchForm(request.GET)
			# Check if the form is valid:
			if form.is_valid():
				# Maping the Search From to our variables and intialization 
				search_category_object = None
				# Represent the Products
				page_list = None
				total_results = 0
				original_search_text = form.cleaned_data['search_query']
				search_text = original_search_text.strip()
				max_price = form.cleaned_data['max_price']
				search_category_name = form.cleaned_data['search_category']
				is_exact_match = form.cleaned_data['is_exact_match']
				show_count = form.cleaned_data['show_count']
	
				if  search_category_name != "None" and search_category_name != "":
					search_category_object = get_object_or_404(Category, name=search_category_name)
				
				if is_exact_match == False:
					# Replacing Spaces with | to search on each word included separetly 
					search_text = re.sub(r' +',"|",search_text)
				
				# if A SearchText is entered
				if search_text != '' or search_text == None:

					if search_category_object:
						if max_price == None:
							# Do Search based on SearchText + Category
							page_list = Product.objects.filter(name__iregex=r'('+search_text+r')').filter(is_published=True).filter(categories__in=[search_category_object])
						else:
							# Do Search based on SearchText + Category + Max
							page_list = Product.objects.filter(name__iregex=r'('+search_text+r')').filter(is_published=True).filter(categories__in=[search_category_object]).filter(price__lte=max_price)
					else:
						if max_price == None:
							# Do Search based on SearchText only
							page_list = Product.objects.filter(name__iregex=r'('+search_text+r')').filter(is_published=True)
						else:
							# Do Search based on SearchText + MAX
							page_list = Product.objects.filter(name__iregex=r'('+search_text+r')').filter(is_published=True).filter(price__lte=max_price)
				# if no SearchText is entered
				else:
					if search_category_object:
						if max_price == None:
							# Do Search based on Category only
							page_list = Product.objects.filter(categories__in=[search_category_object],is_published=True)
						else:
							# Do Search based on Category + MAX
							page_list = Product.objects.filter(is_published=True).filter(categories__in=[search_category_object]).filter(price__lte=max_price)
					else:
						if max_price == None:
							# Do Search based on NOTHING Selcted
							start_search='StartSearch'
							context = {'categories': categories,'start_search':start_search}
							return render(request,'product/search.html',context)
						else: 
							# Do Search based on MAX only
							page_list = Product.objects.filter(is_published=True).filter(price__lte=max_price)

				# Getting the number of results
				if page_list == None:
					total_results = 0
				else:
					total_results = page_list.count()
				

				# handeling Paganation & Items count per page
				if show_count:
					paginator = Paginator(page_list, show_count)
				else:
					 paginator = Paginator(page_list, 10)
					 show_count = 10

				page = request.GET.get('page')
				try:
					page_list = paginator.page(page)
				except PageNotAnInteger:
					# If page is not an integer, deliver first page.
					page_list = paginator.page(1)
				except EmptyPage:
					# If page is out of range (e.g. 9999), deliver last page of results.
					page_list = paginator.page(paginator.num_pages)

				# Fixing the proplem of the reptitave Page attribute in URL
				url_without_page = request.GET.copy()
				if 'page' in url_without_page:
					del url_without_page['page']

				# Final Context Variables to Send back
				context = {
					'categories': categories,
					'page_list': page_list,
					'category':search_category_object,
					'original_search_text':original_search_text,
					'max_price':max_price,
					'is_exact_match':is_exact_match,
					'total_results':total_results,
					'show_count':show_count,
					'url_without_page':url_without_page,
				}

				return render(request,'product/search.html', context)
			else:
				print ("***************** NOT VALID *********************")
				context = {'categories': categories,}
				return render(request,'product/search.html',context)
		else:
			print ("***************** NOT GET *********************")
			return 

product/templates/product/category_list.html
{% extends "base.html" %}
{% load staticfiles %}


{% block title %}  
	Categories
{% endblock %}


{% block content %}  
	  

  <!-- Bread Crumb STRAT -->
  <div class="container">
    <div class="bread-crumb mtb-30 center-xs">
      <div class="page-title">Categories</div>
      <div class="bread-crumb-inner right-side float-none-xs">
        <ul>
          <li><a href="/">Home</a><i class="fa fa-angle-right"></i></li>
          <li><span>Categories List</span></li>
        </ul>
      </div>
    </div>
  </div>
  <!-- Bread Crumb END --> 
<br/>
<br/>

  <!-- CONTAIN START -->
  <section>
    <div class="container">
      <div class="sub-banner-block center-xs">
        
        <div class="row m-0">
        {% for category in page_list %}
	        	{% if forloop.counter|divisibleby:"3" %}
	      			<div class="row m-0">
	     		  {% endif %}
			          <div class="col-sm-4 p-0">
			            <div class="sub-banner sub-banner1 " style="visibility: visible; animation-name: zoomIn;">
			              <a href="{{ category.get_absolute_url }}">
			                <img src="{% if category.image %}{{ category.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}"   Image" style="width: auto; height: 420px; "> 
			                <div class="sub-banner-detail">
			                  <div class="sub-banner-title">{{ category.name|slice:":20" }}</div>
			                  <div class="sub-banner-subtitle">Click to See all Products ({{category.products.count}})</div>
			                </div>
			              </a>
			            </div>
			          </div>
	        	{% if forloop.counter|divisibleby:"3" %}
	      			</div>
	     		  {% endif %}
		{% endfor %}
        </div>
        
        {% include '_paginator.html' %}
      </div>
    </div>
  </section>


</br>



{% endblock %}

product/templates/product/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
	Product Details
{% endblock %}

{% block content %}  



  <!-- Bread Crumb STRAT -->
  <div class="container">
    <div class="bread-crumb mtb-30 center-xs">
      <div class="page-title">Product Details</div>
      <div class="bread-crumb-inner right-side float-none-xs">
        <ul>
          <li><a href="/">Home</a><i class="fa fa-angle-right"></i></li>
          <li><span>{{ product.name }}</span></li>
        </ul>
      </div>
    </div>
  </div>
  <!-- Bread Crumb END -->


  
  <!-- CONTAIN START -->
  <section>
    <div class="container">
      <div class="row">
        <div class="col-md-5 col-sm-5 mb-xs-30">
          <div class="fotorama" data-nav="thumbs" data-allowfullscreen="native">
           <a href="{{ product.get_absolute_url }}"><img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}"> </a>
           <a href="#"><img src="images/2.jpg" alt="Pioneer"></a>
           <a href="#"><img src="images/3.jpg" alt="Pioneer"></a>
          </div>
        </div>
        <div class="col-md-7 col-sm-7">
          <div class="row">
            <div class="col-xs-12">
              <div class="product-detail-main">
                <div class="product-item-details">
                  <h1 class="product-item-name">{{ product.name }}</h1>
                  <div class="price-box">
                    <span class="price">${% if product.is_discounted %} {{ product.discounted_price}} {% else %}{{ product.price }} {%endif%}</span>
                    {% if product.is_discounted %}
                    	<del class="price old-price">${{ product.price }}</del>
                    {%endif%}
                  </div>

                  <div class="product-info-stock-sku">
	                    <div>
	                      <label>Availability: </label>
	                      <span class="info-deta">In stock {% if product.stock%} ({{ product.stock }}) {% endif %}</span>
	                    </div>
	                 {% if product.model or product.model != '' %}
		                    <div>
		                      <label>SKU/Model: </label>
		                      <span class="info-deta">{{ product.model}} </span>
		                    </div>
		              {% endif %}
                  </div>

                  <div class="product-info-stock-sku">
	                    <div>
	                      <label>Categroies Related: </label>
	                      <span class="info-deta">
	                      	{% for category in product.categories.all %} 
								<a href="{{ category.get_absolute_url }}">{{ category.name }}, </a>
							{% endfor %}
	                      </span>
	                    </div>

                  </div>

                  <p>{{ product.description|linebreaks }}</p>
                <form action="{% url "cart:cart_add" product.id %}" method="post">
                	{% csrf_token %}
                	<input id="id_update" name="update" type="hidden" value="False" />
                  <div class="mb-40">
                    <div class="product-qty">
                      <label for="qty">Qty:</label>
                      <div class="custom-qty">
                        <button onclick="var result = document.getElementById('qty'); var qty = result.value; if( !isNaN( qty ) &amp;&amp; qty &gt; 1 ) result.value--;return false;" class="reduced items" type="button"> <i class="fa fa-minus"></i> </button>
                        <input type="text" class="input-text qty" title="Qty" value="1" maxlength="8" id="qty" name="quantity">
                        <button onclick="var result = document.getElementById('qty'); var qty = result.value; if( !isNaN( qty )) result.value++;return false;" class="increase items" type="button"> <i class="fa fa-plus"></i> </button>
                      </div>
                    </div>
                    <div class="bottom-detail cart-button">
                      <ul>
                        <li class="pro-cart-icon">
                           <button type="submit" title="Add to Cart" class="btn-black"><span></span>Add to Cart</button>
                        </li>
                      </ul>
                    </div>
                  </div>
				</form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>


{% if related_products|length > 0 %}

  <div class="container">
    <div class=" mtb-30 center-xs">
	    <br/>
			<hr/>
		<br/>
    </div>
  </div>


  <section class="pb-95">
    <div class="container">
      <div class="product-slider owl-slider">
        <div class="row">
          <div class="col-xs-12">
            <div class="heading-part align-center mb-40">
              <h2 class="main_title">Related Products</h2>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="product-slider-main position-r">
            <div class="owl-carousel pro_cat_slider">

            	{% for r_product in related_products %} 
	              <div class="item">
	                <div class="product-item">
	                  <div class="product-image">
	                    {% if r_product.is_discounted %} <div class="sale-label"><span>Sale</span></div>{%endif%}
	                    <a href="{{ r_product.get_absolute_url }}">
	                      <img src="{% if r_product.image %}{{ r_product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" >
	                    </a>
	                  </div>
	                  <div class="product-item-details">
	                    <div class="product-item-name">
	                      <a href="product-page.html">{{ r_product.name }}</a>
	                    </div>

	                    <div class="price-box">
                    		<span class="price">${% if r_product.is_discounted %} {{ r_product.discounted_price}} {% else %}{{ r_product.price }} {%endif%}</span>
                    		{% if r_product.is_discounted %}
                    			<del class="price old-price">${{ r_product.price }}</del>
                    		{%endif%}
                  		</div>

	                  </div>
	                  <div class="product-detail-inner">
	                    <div class="detail-inner-left left-side">
	                      <ul>
	                        <li class="pro-cart-icon">
	                          <form action="{% url "cart:cart_add" product.id %}" method="post">
	                          	{% csrf_token %}
                				<input id="id_update" name="update" type="hidden" value="False" />
                				<input id="id_quantity" name="quantity" type="hidden" value="1" />
	                            <button type="submit" title="Add to Cart"><span></span>Add to Cart</button>
	                          </form>
	                        </li>
	                      </ul>
	                    </div>
	                  </div>
	                </div>
	              </div>
	            {% endfor %}

            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
 {% endif %}
  <!-- CONTAINER END --> 			 
		
<!--
				<form action="{% url "cart:cart_add" product.id %}" method="post">
				  {{ cart_product_form }}
				  {% csrf_token %}
  				<input type="submit" value="Add to cart">
  				</form>
-->


{% endblock %}

product/templates/product/product_list.html
{% extends "base.html" %}
{% load staticfiles %}


{% block title %}  
	{% if category %}{{ category.name }}
	{% else %}Products
	{% endif %}
{% endblock %}


{% block content %}  
	  




  <!-- Bread Crumb STRAT -->
  <div class="container">
    <div class="bread-crumb mtb-30 center-xs">
      <div class="page-title">
		{% if category %}{{ category.name }} Products
		{% else %} All Products
		{% endif %}
      </div>
      <div class="bread-crumb-inner right-side float-none-xs">
        <ul>
          <li><a href="/">Home</a><i class="fa fa-angle-right"></i></li>
          <li><span>Products</span></li>
        </ul>
      </div>
    </div>
  </div>
  <!-- Bread Crumb END --> 




 <section class="pb-95">
    <div class="container">
      <div class="row">
        <div class="col-md-3 col-sm-4 mb-xs-30">	
          <div class="sidebar-block">

			<form class="form-horizontal" role="form"  action="/search/" method="GET">
			{% csrf_token %}
	            <div class="sidebar-box mb-40">
	              <form>
	                <div class="search-box">
	                  <input type="text" name="search_query" placeholder="Search entire store here..." class="input-text" value="{{original_search_text}}" >
	                  <button type="submit" class="search-btn"></button>
	                </div>
	              </form>
	            </div>
			</form>

            <div class="sidebar-box listing-box mb-40">
              <span class="opener plus"></span>
              <div class="main_title sidebar-title">
                <h3><span>All Categories</span></h3>
              </div>
              <div class="sidebar-contant">
                <ul>
                	<li {% if not category %} class="active" {% endif %}><a href="{% url "product:product_list" %}?show_count={{show_count}}">All</a> </li>
				          {% for c in categories %} 
                  		<li  {% if category.slug == c.slug %} class="active" {% endif %}><a  href="{{ c.get_absolute_url }}?show_count={{show_count}}">{{ c.name|title }} <span>({{c.page_list.count}})</span></a></li>
					        {% endfor %}
                </ul>
              </div>
            </div>

          </div>
        </div>



        <div class="col-md-9 col-sm-8">

		<form class="form-horizontal" role="form"  action="" method="GET">
		{% csrf_token %}
          <div class="shorting mb-30">
            <div class="row">
              <div class="col-md-6">
                <div class="view">
                  <div class="list-types grid active">
                    <a href="{{request.get_full_path}}">
                      <div class="grid-icon list-types-icon"></div>
                    </a> 
                  </div>
                  <div class="list-types list ">
                    <a href="{{request.get_full_path}}">
                      <div class="list-icon list-types-icon"></div>
                    </a> 
                  </div>
                </div>
                <div class="short-by float-right-sm">
                  <span>Sort By</span>
                  <div class="select-item">
                    <select name="sort_list" onchange="this.form.submit();">
                      <option value="by_name_desc" selected="selected">Name (A to Z)</option>
                      <option value="by_name_asc">Name(Z - A)</option>
                      <option value="by_price_desc">price(low&gt;high)</option>
                      <option value="by_price_asc">price(high &gt; low)</option>
                    </select>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="show-item right-side float-left-sm">
                  <span>Show</span>
                  <div class="select-item">
                    <select name="show_count" onchange="this.form.submit();">
                      <option value="30" {% if show_count == 30%} selected="selected" {%endif%}>30</option>
                      <option value="20" {% if show_count == 20%} selected="selected" {%endif%}>20</option>
                      <option value="10" {% if show_count == 10 or show_count == None%} selected="selected" {%endif%}>10</option>
                    </select>
                  </div>
                  <span>Per Page</span>
                </div>
              </div>
            </div>
          </div>
      	</form>


          <div class="product-listing">
            <div class="row mlr_-20">
      					{% for product in page_list %}                   
			              <div class="col-md-4 col-xs-6 plr-20">
			                <div class="product-item">
			                  <div class="product-image">
			                  	{% if product.is_discounted %}
			                    	<div class="sale-label"><span>Sale</span></div>
			                    {% endif %}
			               		{% if product.is_featured %}
			                    	<div class="featured-label"><span>Featured</span></div>
			                    {% endif %}
								<a href="{{ product.get_absolute_url }}">    
					   				<img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" Image" style="width: auto; height: 350px; "  alt="Image">        
					   			</a> 
			                  </div>
			                  <div class="product-item-details">
			                    <div class="product-item-name">
			                      <a href="{{ product.get_absolute_url }}">{{ product.name|slice:":30" }}</a>
			                    </div>
			                    <div class="price-box">
			                    {% if product.is_discounted %}
			                      	<span class="price">SAR {{ product.discounted_price }}</span>
			                      	<del class="price old-price">SAR {{ product.price }}</del>
			                     {% else %}
			                    	<span class="price">SAR {{ product.price }}</span>
			                    {% endif %}
			                    </div>
			                  </div>
			                  <div class="product-detail-inner">
			                    <div class="detail-inner-left left-side">
			                      <ul>
			                        <li class="pro-cart-icon">
			                          <form action="{% url "cart:cart_add" product.id %}" method="post">
                                  {% csrf_token %}
                                  <input id="id_update" name="update" type="hidden" value="False" />
                                  <input id="id_quantity" name="quantity" type="hidden" value="1" />
			                            <button  type="submit" title="Add to Cart"><span></span>Add to Cart</button>
			                          </form>
			                        </li>
			                      </ul>
			                    </div>
			                    <div class="detail-inner-left right-side">
			                      <ul>
			                        <li class="pro-wishlist-icon active"><a href="#"></a></li>
			                        <li class="pro-compare-icon"><a href="#"></a></li>
			                      </ul>
			                    </div>
			                  </div>
			                </div>
			              </div>
					{% endfor %}
            </div>

            {% include '_paginator.html' %}
          </div>
        </div>
      </div>
    </div>
  </section>
 
  <!-- CONTAINER END --> 



{% endblock %}