cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.cart_detail, name='cart_detail'),
	url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
	url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

contact/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [ 
		url(r'^$', views.new_message,name='contact'),
	]

ecommerce/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^career/', include('career.urls', namespace='career')),
    url(r'^contact/', include('contact.urls', namespace='contact')),
    url(r'^about/', include('static_pages.urls', namespace='static_pages')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^', include('product.urls', namespace='product')),
]
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

contact/models.py
from django.db import models

from django.utils.timezone import now
from django.utils import timezone
# For the country Field
from django_countries.fields import CountryField
#Used for the Telephone Field validation
from django.core.validators import RegexValidator



class Contact(models.Model):
	CHOICES = (('Business Offer','Business Offer'), ('Complain','Complain'),('Question','Question'))
	phone_regex = RegexValidator(regex=r'^\+?1?\d{8,15}$', 
		message="Phone number must be entered in the format: '+999999'. Min of 5 digits and max Up to 15 digits allowed.")

	first_name = models.CharField(max_length=150)
	middle_name = models.CharField(max_length=150, blank=True, null=True)
	last_name = models.CharField(max_length=150)
	phone = models.CharField(validators=[phone_regex], max_length=16) 
	email = models.EmailField(max_length=50, blank=True, null=True)
	message = models.CharField(max_length=500, help_text="Please Enter your message")
	message_type = models.CharField(max_length=30, choices=CHOICES)
	applied_timestamp = models.DateField(auto_now_add=True);

	class Meta:
		ordering = ("applied_timestamp",)

	def __str__(self):
		return self.message_type

contact/forms.py
from django import forms
from django.forms import ModelForm
from .models import Contact


'''
Form for Subitting a Contact Message
'''
class ContactForm(ModelForm): 
	
	class Meta:
		model = Contact
		fields = ['first_name', 'middle_name' ,'last_name' , 'phone' ,'email' ,'message' ,'message_type']

contact/views.py
from django.shortcuts import render, get_object_or_404
#used for my customized created models
from .models import Contact
from .forms import ContactForm
#used for sending emails
from django.core.mail import send_mail
from django.conf import settings


def new_message(request):
		"""
			Submit a new contact Message to DB
		"""
		# Get the context from the request
		if request.method == 'POST':
			# Create a form instance and populate it with data from the request (binding):
			form=ContactForm(request.POST)
			if form.is_valid():

					contact = form.save(commit=False)
					contact.first_name = form.cleaned_data['first_name']
					contact.middle_name = form.cleaned_data['middle_name']
					contact.last_name = form.cleaned_data['last_name']
					contact.phone = form.cleaned_data['phone']
					contact.email = form.cleaned_data['email']
					contact.message = form.cleaned_data['message']
					contact.message_type = form.cleaned_data['message_type']
					contact.save()
					context = {
						'message':"Your Message has been Submitted Successfully", 
					}

					# Handeling Email attributes and sending one
					contact_message = form.cleaned_data['message']
					contact_firstName = form.cleaned_data['first_name']
					contact_email = form.cleaned_data['email']
					email_subject = 'My ECommerce - New Contact Submitted'
					email_message = '%s %s' %(contact_message, contact_firstName)
					email_from = contact_email 
					email_to = [settings.EMAIL_HOST_USER]
					send_mail(email_subject,email_message,email_from, email_to, fail_silently=True)

					return render(request, "contact/contact_status.html", context)	
		else:
			# Not a POST so Generate New Empty Form from Contact Class
			form = ContactForm()

		context = {
			'form': form,
		}
		return render(request, "contact/contact.html", context)

contact/templates/contact/contact.html
{% extends "base.html" %}
{% load static %}

{% block title %}
	Contact
{% endblock %}

{% block content %}  



  <!-- BANNER STRAT -->
  <div class="banner contact-banner"></div>
  <!-- BANNER END -->


  <!-- Bread Crumb STRAT -->
  <div class="container">
    <div class="bread-crumb mtb-30 center-xs">
      <div class="page-title">Contact</div>
      <div class="bread-crumb-inner right-side float-none-xs">
        <ul>
          <li><a href="/">Home</a><i class="fa fa-angle-right"></i></li>
          <li>Contact</i></li>
        </ul>
      </div>
    </div>
  </div>
  <!-- Bread Crumb END --> 



  <section>
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="map">
            <div class="map-part">
              <div id="map" class="map-inner-part"></div>
              <!--<style>#gmap_canvas img{max-width:none!important;background:none!important}</style><a class="google-map-code" href="http://www.themecircle.net" id="get-map-data">themecircle</a>--></div>
              <script type="text/javascript" src="http://maps.google.com/maps/api/js?key=AIzaSyC_G1wZMKrwyHHOteMdVwCy82Qm4Pp7vyI&callback=initMap"></script> 
              <script type="text/javascript">
                // When the window has finished loading create our google map below
                google.maps.event.addDomListener(window, 'load', init);
            
                function init() {
                  // Basic options for a simple Google Map
                  // For more options see: https://developers.google.com/maps/documentation/javascript/reference#MapOptions
                  
                  var mapOptions = {
                      // How zoomed in you want the map to start at (always required)
                      zoom: 14,
                      scrollwheel:false,

                      // The latitude and longitude to center the map (always required)
                      center: new google.maps.LatLng(24.688414, 46.754332), // Riyadh
                      
                      // How you would like to style the map. 
                      // This is where you would paste any style found on Snazzy Maps.
                      styles: [{"featureType":"all","elementType":"labels.text.fill","stylers":[{"saturation":36},{"color":"#666666"},{"lightness":40}]},{"featureType":"all","elementType":"labels.text.stroke","stylers":[{"visibility":"on"},{"color":"#000000"},{"lightness":16}]},{"featureType":"all","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"administrative","elementType":"geometry.fill","stylers":[{"color":"#000000"},{"lightness":20}]},{"featureType":"administrative","elementType":"geometry.stroke","stylers":[{"color":"#000000"},{"lightness":17},{"weight":1.2}]},{"featureType":"landscape","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":20}]},{"featureType":"poi","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":21}]},{"featureType":"road.highway","elementType":"geometry.fill","stylers":[{"color":"#000000"},{"lightness":17}]},{"featureType":"road.highway","elementType":"geometry.stroke","stylers":[{"color":"#666666"},{"lightness":100},{"weight":0.2}]},{"featureType":"road.arterial","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":18}]},{"featureType":"road.local","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":16}]},{"featureType":"transit","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":19}]},{"featureType":"water","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":17}]}]
                  };

                  // Get the HTML DOM element that will contain your map 
                  // We are using a div with id="map" seen below in the <body>
                  var mapElement = document.getElementById('map');

                  // Create the Google Map using our element and options defined above
                  var map = new google.maps.Map(mapElement, mapOptions);

                  // Let's also add a marker while we're at it
                
                  var marker = new google.maps.Marker({map: map,position: new google.maps.LatLng(24.688414, 46.754332)});infowindow = new google.maps.InfoWindow({content:"<b>Webcotheme</b><br/>144 , Allen st<br/> new yourk" });google.maps.event.addListener(marker, "click", function(){infowindow.open(map,marker);});infowindow.open(map,marker);}google.maps.event.addDomListener(window, 'load', init_map);
              </script> 
          </div>
        </div>
      </div>
    </div>
  </section>




  <section class="pt-95 client-main align-center">
    <div class="container">
      <div class="contact-info">
        <div class="row m-0">
          <div class="col-sm-4 p-0">
            <div class="contact-box">
              <div class="contact-icon contact-phone-icon"></div>
              <span><b>Tel</b></span>
              <p>00966 556 789 / 00966 116 788</p>
            </div>
          </div>
          <div class="col-sm-4 p-0">
            <div class="contact-box">
              <div class="contact-icon contact-mail-icon"></div>
              <span><b>Mail</b></span>
              <p>contact@domain.com </p>
            </div>
          </div>
          <div class="col-sm-4 p-0">
            <div class="contact-box">
              <div class="contact-icon contact-open-icon"></div>
              <span><b>Open</b></span>
              <p>Sunday – Thursday: 9:00 – 18:00</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>



</br>


<form action="" class="main-form full" method="POST" >
{% csrf_token %}
  <section class="checkout-section pb-95">
    <div class="container">
      <div class="row">
		<div class="col-xs-12">
         <div class="checkout-content" >


            <div class="row">
              <div class="col-xs-12">
                <div class="heading-part align-center">
                    <h2 class="heading">LEAVE A MESSAGE!</h2>
                </div>
              </div>
            </div>
 


            <div class="row">
              <div class="col-lg-6 col-md-8 col-sm-8 col-lg-offset-3 col-sm-offset-2">


                  <div class="mb-20">
                    <div class="row ">
                    	<div class="col-sm-12">
                        	<div class="input-box">
                    			{{form.non_field_errors}} 
                    		</div>
                 		 </div>
                    </div>
                  </div>

                  <div class="mb-20">
                    <div class="row">

                      <div class="col-sm-6">
                        <div class="input-box {% if form.first_name.errors %} has-error {% endif %}">
                        	<input  maxlength="150" 
                        	name="first_name"  
                        			id="id_first_name" 
                        			type="text" 
                        			{% if form.first_name.value %} value="{{form.first_name.value}}" {% endif %} 
                        			placeholder="First Name*" 
                        			class="form-control "
                        			/>
                        </div>
                      </div>
                      <div class="col-sm-6">
                        <div class="input-box {% if form.middle_name.errors %} has-error {% endif %}" >
                          	<input 	id="id_middle_name" 
                          			maxlength="150" 
                          			name="middle_name" 
                          			type="text" 
                          			{% if form.middle_name.value %} value="{{form.middle_name.value}}" {% endif %} 
                          			placeholder="Middle Name" 
                          			class="form-control" 
                          			/>
                        </div>
                      </div>

                      <div class="col-sm-6">
                        <div class="input-box {% if form.last_name.errors %} has-error{% endif %}">
                          	<input id="id_last_name" 
                          			maxlength="150" 
                          			name="last_name" 
                          			type="text" 
                          			{% if form.last_name.value %} value="{{form.last_name.value}}" {% endif %} 
                          			placeholder="Last Name*" 
                          			class="form-control"
                          			/>
                        </div>
                      </div>

                      <div class="col-sm-6">
                        <div class="input-box {% if form.email.errors %} has-error{% endif %}">
                          	<input 	id="id_email" 
                          			maxlength="50" 
                          			name="email" 
                          			type="email" 
                          			{% if form.email.value %} value="{{form.email.value}}" {% endif %}
                          			placeholder="Email Address*" 
                          			class="form-control"
                          			/>
                        </div>
                      </div>

                      <div class="col-sm-6">
                        <div class="input-box {% if form.phone.errors %} has-error{% endif %}">
                        <input 	id="id_phone" 
                        		maxlength="16" 
                        		name="phone" 
                        		placeholder="Phone*" 
                        		type="text" 
                        		{% if form.phone.value %} value="{{form.phone.value}}" {% endif %}
                        		class="form-control"
                        		/>
                        <span>Tel. Format: +XXX YYY YYY</span>
                        </div>
                      </div>

                      <div class="col-sm-6">
                        <div class="input-box {% if form.message_type.errors %} has-error {% endif %}">
                          <select 	id="id_message_type" name="message_type" class="form-control">
                          		{% if form.message_type.value == None %}
                          			<option value=""   selected="selected"  >Select a Reason*</option>
                          		{% endif %}
            							    <option value="Business Offer" {% if form.message_type.value == 'Business Offer' %}  selected="selected"  {% endif %}>Business Offer</option>
            							    <option value="Complain" {% if form.message_type.value == 'Complain' %}  selected="selected"  {% endif %}>Complain</option>
            							    <option value="Question" {% if form.message_type.value == 'Question' %}  selected="selected"  {% endif %}>Question</option>
						              </select>
						              <span> Reason for the Message</span>
                        </div>
                       </div>

                      <div class="col-sm-12">
                        <div class="input-box {% if form.message.errors %} has-error {% endif %}">
                          	<textarea cols="60" id="id_message" 
                          			maxlength="500" 
                          			name="message" rows="6" 
                          			placeholder="Please Enter Your Message" 
                          			class="form-control"
                          			>{% if form.message.value %} {{form.message.value}} {% endif %}</textarea>
                        </div>
                      </div>

                    </div>
                  </div>

                  <button type="submit" value="Submit" class="btn-black"  name="submit">Send</button>
          </div>
        </div>
      </div>
    </div>
  </section>
</form>

























  {% endblock %}

contact/templates/contact/contact_status.html
{% extends "base.html" %}
{% load static %}

{% block title %}
	Career
{% endblock %}

{% block content %}  


  <!-- Bread Crumb STRAT -->
  <div class="container">
    <div class="bread-crumb mtb-30 center-xs">
      <div class="page-title">Contact</div>
      <div class="bread-crumb-inner right-side float-none-xs">
        <ul>
          <li><a href="/">Home</a><i class="fa fa-angle-right"></i></li>
          <li><a href="/contact/">Contact</a><i class="fa fa-angle-right"></i></li>
          <li>Submition Status</li>
        </ul>
      </div>
    </div>
  </div>
  <!-- Bread Crumb END --> 

   <section class="pb-95">
    <div class="container">

              <div class="col-xs-12">
                <div class="heading-part align-center">
                    <h2 class="heading">Thank You!</h2>
                </div>
              </div>

            <div class="row">
              <div class="col-lg-10 col-md-8 col-sm-8 col-lg-offset-1 col-sm-offset-1">
                <div class="payment-option-box mb-30">
                  <div class="payment-option-box-inner ">
                    <div class="payment-top-box">
                      <div class="radio-box left-side">
                        <label for="paypal">{{ message }}</label>
                      </div>
                    </div>
                    <p>Please feel free to contact us via email or phone <span> <a href="/contact/">Click Here</a> </span> </p>
                  </div>
                </div>
               </div>
            </div>
    </div>
</section>
<!-- CONTENTS ENDS -->

{% endblock %}